#!/bin/bash
# changing window focus

rcmd - j : yabai -m window --focus south
rcmd - k : yabai -m window --focus north
rcmd - h : yabai -m window --focus west
rcmd - l : yabai -m window --focus east

rcmd - s : yabai -m display --focus west
rcmd - g : yabai -m display --focus east

rcmd - n : /Users/jaredmoulton/.config/scripts/space_focus_next
rcmd - p : /Users/jaredmoulton/.config/scripts/space_focus_prev

rcmd - m : yabai -m space $(active_space) --label main

# browswer
rshift + rcmd - b : /Users/jaredmoulton/.config/scripts/focus_app "Safari"

# terminal
rshift + rcmd - t : /Users/jaredmoulton/.config/scripts/focus_app "WezTerm"

# discord
rshift + rcmd - d : /Users/jaredmoulton/.config/scripts/focus_app "Discord"

# spotify
rshift + rcmd - s : /Users/jaredmoulton/.config/scripts/focus_app "Spotify"

# passwrod manager
rshift + rcmd - p : /Users/jaredmoulton/.config/scripts/focus_app "1Password"

# Messages
# rshift + rcmd - m : /Users/jaredmoulton/.config/scripts/focus_app "Messages"

# Finder
rshift + rcmd - f : /Users/jaredmoulton/.config/scripts/focus_app "Finder"

# Word
rshift + rcmd - w : /Users/jaredmoulton/.config/scripts/focus_app "Microsoft Word"

# Word
rshift + rcmd - z : /Users/jaredmoulton/.config/scripts/focus_app "Zed"

rshift + rcmd - y : /Users/jaredmoulton/.config/scripts/focus_app "YouTube"

rshift + rcmd - c : /Users/jaredmoulton/.config/scripts/focus_app "Canvas"

rshift + rcmd - a : /Users/jaredmoulton/.config/scripts/focus_app "ChatGPT"

rshift + rcmd - m : /Users/jaredmoulton/.config/scripts/focus_app "Gmail"

rshift + rcmd - g : /Users/jaredmoulton/.config/scripts/focus_app "GitHub"

rshift + rcmd - r : /Users/jaredmoulton/.config/scripts/focus_app "Rust"

rshift + rcmd - l : /Users/jaredmoulton/.config/scripts/focus_app "Leviathan"


# Modifying the Layout

 # rotate layout clockwise
rcmd - r : yabai -m space --rotate 270

# flip along y-axis
rcmd - y : yabai -m space --mirror y-axis

# flip along x-axis
rcmd - x : yabai -m space --mirror x-axis

# toggle window float
rcmd - t : yabai -m window --toggle float --grid 4:4:1:1:2:8

# Modifying Window Size

# maximize a window
rcmd - z : yabai -m window --toggle zoom-fullscreen

# Make window native fullscreen
rcmd - f : yabai -m window --toggle native-fullscreen

# balance out tree of windows (resize to occupy same area)
rcmd - e : yabai -m space --balance

# ctrl + rcmd - h : yabai -m window --resize left:-50:0; \
#                   yabai -m window --resize right:-50:0
# ctrl + rcmd - j : yabai -m window --resize bottom:0:50; \
#                   yabai -m window --resize top:0:50
# ctrl + rcmd - k : yabai -m window --resize top:0:-50; \
#                   yabai -m window --resize bottom:0:-50
# ctrl + rcmd - l : yabai -m window --resize right:50:0; \
#                   yabai -m window --resize left:50:0

# Enable / Disable gaps in current workspace
ctrl + rcmd - g : yabai -m space --toggle padding; yabai -m space --toggle gap

shift + rcmd - 2 : yabai -m window --grid 1:2


# swap windows
lshift + rcmd - j : yabai -m window --swap south
lshift + rcmd - k: yabai -m window --swap north
lshift + rcmd - h: yabai -m window --swap west
lshift + rcmd - l : yabai -m window --swap east

# lshift + ctrl + rcmd - j : yabai -m window --warp south
# lshift + ctrl + rcmd - k: yabai -m window --warp north
# lshift + ctrl + rcmd - h: yabai -m window --warp west
# lshift + ctrl + rcmd - l : yabai -m window --warp east

# move window to display left and right
lshift + rcmd - s : yabai -m window --display west; yabai -m display --focus west
lshift + rcmd - g : yabai -m window --display east; yabai -m display --focus east

# Goto previous and next spaces
rcmd - p : yabai -m window --space prev; yabai -m space --focus prev;
rcmd - n : yabai -m window --space next; yabai -m space --focus next;

lshift + rcmd - 1 : yabai -m window --space 1; yabai -m space --focus 1
lshift + rcmd - 2 : yabai -m window --space 2; yabai -m space --focus 2
lshift + rcmd - 3 : yabai -m window --space 3; yabai -m space --focus 3
lshift + rcmd - 4 : yabai -m window --space 4; yabai -m space --focus 4
lshift + rcmd - 5 : yabai -m window --space 5; yabai -m space --focus 5
lshift + rcmd - 6 : yabai -m window --space 6; yabai -m space --focus 6

# Move window to a space and then focus the sace
lshift + rcmd - 1 : yabai -m window --space 1; yabai -m space --focus 1
lshift + rcmd - 2 : yabai -m window --space 2; yabai -m space --focus 2
lshift + rcmd - 3 : yabai -m window --space 3; yabai -m space --focus 3
lshift + rcmd - 4 : yabai -m window --space 4; yabai -m space --focus 4
lshift + rcmd - 5 : yabai -m window --space 5; yabai -m space --focus 5
lshift + rcmd - 6 : yabai -m window --space 6; yabai -m space --focus 6

rcmd - 1 : yabai -m space --focus 1
rcmd - 2 : yabai -m space --focus 2
rcmd - 3 : yabai -m space --focus 3
rcmd - 4 : yabai -m space --focus 4
rcmd - 5 : yabai -m space --focus 5
rcmd - 6 : yabai -m space --focus 6
rcmd - 7 : yabai -m space --focus 7
rcmd - 8 : yabai -m space --focus 8

ctrl + rcmd - k : yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $has_index > 0 then nth($has_index - 1).id else nth($array_length - 1).id end' \
  | xargs -I{} yabai -m window --focus {}

ctrl + rcmd - j : yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $array_length - 1 > $has_index then nth($has_index + 1).id else nth(0).id end' \
  | xargs -I{} yabai -m window --focus {}


# starting and stopping yabai
ctrl + rcmd - q : brew services stop yabai
ctrl + rcmd - s : brew services start yabai

# Restart Yabai
lshift + ctrl + rcmd - r : \
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Audio
rcmd - f10 : SwitchAudioSource -s "Jared’s AirPods Pro"
rcmd - f11 : SwitchAudioSource -s AT2020USB+
rcmd - f12 : SwitchAudioSource -s "Plugable Audio"
