#!/bin/bash
# changing window focus

rcmd - j : yabai -m window --focus south
rcmd - k : yabai -m window --focus north
rcmd - h : yabai -m window --focus west
rcmd - l : yabai -m window --focus east

rcmd - s : yabai -m display --focus west
rcmd - g : yabai -m display --focus east


# Modifying the Layout

 # rotate layout clockwise
rcmd - r : yabai -m space --rotate 270

# flip along y-axis
rcmd - y : yabai -m space --mirror y-axis

# flip along x-axis
rcmd - x : yabai -m space --mirror x-axis

# toggle window float
rcmd - t : yabai -m window --toggle float --grid 4:4:1:1:2:8

# Modifying Window Size

# maximize a window
rcmd - z : yabai -m window --toggle zoom-fullscreen

# Make window native fullscreen
rcmd - f : yabai -m window --toggle native-fullscreen

# balance out tree of windows (resize to occupy same area)
rcmd - e : yabai -m space --balance

ctrl + rcmd - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
ctrl + rcmd - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
ctrl + rcmd - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
ctrl + rcmd - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

# Enable / Disable gaps in current workspace
ctrl + rcmd - g : yabai -m space --toggle padding; yabai -m space --toggle gap

shift + rcmd - 2 : yabai -m window --grid 1:2


# swap windows
shift + rcmd - j : yabai -m window --swap south
shift + rcmd - k: yabai -m window --swap north
shift + rcmd - h: yabai -m window --swap west
shift + rcmd - l : yabai -m window --swap east

shift + ctrl + rcmd - j : yabai -m window --warp south
shift + ctrl + rcmd - k: yabai -m window --warp north
shift + ctrl + rcmd - h: yabai -m window --warp west
shift + ctrl + rcmd - l : yabai -m window --warp east

# move window to display left and right
shift + rcmd - s : yabai -m window --display west; yabai -m display --focus west
shift + rcmd - g : yabai -m window --display east; yabai -m display --focus east

rcmd - p : yabai -m window --space prev; yabai -m space --focus prev;
rcmd - n : yabai -m window --space next; yabai -m space --focus next;
shift + rcmd - 1 : yabai -m window --space 1; yabai -m space --focus 1
shift + rcmd - 2 : yabai -m window --space 2; yabai -m space --focus 2
shift + rcmd - 3 : yabai -m window --space 3; yabai -m space --focus 3
shift + rcmd - 4 : yabai -m window --space 4; yabai -m space --focus 4
shift + rcmd - 5 : yabai -m window --space 5; yabai -m space --focus 5
shift + rcmd - 6 : yabai -m window --space 6; yabai -m space --focus 6

rcmd - 1 : yabai -m space --focus 1
rcmd - 2 : yabai -m space --focus 2
rcmd - 3 : yabai -m space --focus 3
rcmd - 4 : yabai -m space --focus 4
rcmd - 5 : yabai -m space --focus 5
rcmd - 6 : yabai -m space --focus 6
rcmd - 7 : yabai -m space --focus 7
rcmd - 8 : yabai -m space --focus 8



# starting and stopping yabai
ctrl + rcmd - q : brew services stop yabai
ctrl + rcmd - s : brew services start yabai

# Restart Yabai
shift + ctrl + rcmd - r : \
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Audio
f11 : SwitchAudioSource -s AT2020USB+
f12 : SwitchAudioSource -s "Plugable Audio"
