#!/bin/bash

if [[ "$1" == "" ]]; then
    search_path=$HOME/programming
else
    search_path=$1
fi

for file_path in $(fd ".git$" $search_path -t d -H -I -a) 
do
    cd $file_path
    cd ..
    git_status=$(git status -s)
    if [[ "$git_status" != "" ]]; then
        echo $file_path
        echo $git_status
        echo
    fi

done

for file_path in $(fd worktrees $search_path -t d -H -I -a); do
    cd $file_path
    cd ..
    for tree in $(basename $(fd . worktrees/ -d 1)); do
        cd $tree
        git_status=$(git status -s)
        if [[ "$git_status" != "" ]]; then
            echo "$(pwd)/$tree"
            echo $git_status
            echo
            cd ..
        fi
    done
done

file_path="$HOME/.config/"
cd $file_path
git_status=$(git status -s)
if [[ "$git_status" != "" ]]; then
    echo $file_path
    echo $git_status
    echo
fi
