#!/bin/bash

if [[ $* == *-p* ]]; then
    file=$(echo $@ | rg "[a-zA-Z/._\d]+\s?$" -o)
    if [[ "$file" != *".md"* ]]; then
        file="$file.md"
    fi
    prevmark $HOME/notes/$file
    exit 0
fi

file=$(basename $1)
path=$(echo $1 | sd "$file" "" | sd "/\s*$" "" )
if [[ "$path" != "" ]]; then
    path="$HOME/notes/$path/"
    if [[ ! -d $path ]]; then
        mkdir -p $path
    fi
else 
    path="$HOME/notes/"
fi
if [[ "$file" != *".md"* ]]; then
    file="$file.md"
fi

nvim $path$file


