#!/bin/bash

sleep 0.5
sessions=$(tmux list-sessions -F '#{session_name}')
current_session=$(tmux display-message -p '#S')
star="*"
white="\s"
space=" "
sessions=$(echo $sessions | sd $current_session$white "$current_session$star ")
echo $sessions

