#!/bin/zsh

### Adapted from @ThePrimeagen dotfiles

get_folders() {
    folders="$HOME/.config/\n"
    search_path="$HOME/programming"
    for file_path in $(fd ".git$" $search_path -t d -H -I -a) 
    do
        cd $file_path
        cd ..
        folders+="$(pwd)\n"
    done

    for file_path in $(fd worktrees $search_path -t d -H -I -a); do
        cd $file_path
        cd ..
        folders+="$(pwd)\n"
    done
    echo -e $folders
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    
    selected=$(get_folders | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    if [[ -d "$selected/worktrees" ]]; then
        for tree in $(basename $(fd . $selected/worktrees -d 1)); do
            tmux new-window -t $selected_name -n $tree -c $selected/$tree
        done
    fi
    exit 0
fi

if ! tmux has-session -t $selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    if [[ -d "$selected/worktrees" ]]; then
        for tree in $(basename $(fd . $selected/worktrees -d 1)); do
            tmux new-window -t $selected_name -n $tree -c $selected/$tree
        done
    fi
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
