#!/bin/bash

### Adapted from @ThePrimeagen dotfiles

get_folders() {
    folders="$HOME/.config/\n"
    search_path="$HOME/Developer/"
    for file_path in $(fd ".git$" $search_path -t d -H -I -a) 
    do
        cd $file_path
        cd ..
        folders+="$(pwd)\n"
    done

    for file_path in $(fd refs $search_path -t d -H -I -a); do
        cd $file_path
        cd ..
        if [[ $(git rev-parse --is-bare-repository) == "true" ]]; then
            folders+="$(pwd)\n"
        fi
    done
    echo -e $folders
}

if [[ -z "$1" ]]; then
    selected=$(get_folders | fzy)
else
    selected="$HOME/Developer/$1"
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected
    # if [[ -d "$selected/refs" ]]; then
    #     trees=$(fd . "$selected/worktrees" -d 1 2> /dev/null)
    #     if [[ -z $trees ]]; then
    #         cd $selected
    #         branches=$(git branch --list)
    #         if [[ "$branches" == *"main"* ]]; then
    #             git worktree add main &> /dev/null
    #         elif [[ "$branches" == *"master"* ]]; then
    #             git worktree add master &> /dev/null
    #         fi
    #     fi
    #     for tree in $(fd . "$selected/worktrees" -d 1); do
			# full_path=$(cat "$tree/gitdir" | sd "\.git" "")
    #         base=$(basename $tree)
    #         tmux new-window -t $selected_name -n $base -c $full_path
    #         if [[-d "$full_path/venv" ]]; then
    #             tmux send-keys -t $selected_name "source $full_path/venv/bin/activate" Enter
    #         fi
    #     done
    # fi
fi

if ! tmux has-session -t "$selected_name " 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    if [[ -d "$selected/venv" ]]; then
        tmux send-keys -t $selected_name "source $selected/venv/bin/activate" Enter
        tmux send-keys -t $selected_name "clear" Enter
    fi
    if [[ -d "$selected/refs" ]]; then
        trees=$(fd . "$selected/worktrees" -d 1 2> /dev/null)
        if [[ -z $trees ]]; then
            cd $selected
            branches=$(git branch --list)
            if [[ "$branches" == *"main"* ]]; then
                git worktree add main &> /dev/null
            elif [[ "$branches" == *"master"* ]]; then
                git worktree add master &> /dev/null
            fi
            fi
        for tree in $(fd . "$selected/worktrees" -d 1); do
			full_path=$(cat "$tree/gitdir" | sd "\.git" "")
            base=$(basename $tree)
            tmux new-window -t $selected_name -n $base -c $full_path
            if [[ -d "$selected/venv" ]]; then
                tmux send-keys -t $selected_name:$tree.1 "source $selected/venv/bin/activate" Enter
                tmux send-keys -t $selected_name "clear" Enter
            fi
        done
    fi
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi
